apiKeyParam: key
languageParam: language

gameHeroes:
    itemizedOnlyParam: itemizedonly
    url: https://api.steampowered.com/IEconDOTA2_570/GetHeroes/v0001/

gameItems:
    url: https://api.steampowered.com/IEconDOTA2_570/GetGameItems/v1/

matchDetails:
    url: https://api.steampowered.com/IDOTA2Match_570/GetMatchDetails/V001/
    matchIdParam: match_id

matchHistory:
    url: https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/V001/
    accountIdParam: account_id
    gameModeParam: game_mode
    heroIdParam: hero_id
    leagueIdParam: league_id
    matchesRequestedParam: matches_requested
    minPlayersParam: min_players
    skillParam: skill
    startAtMatchIdParam: start_at_match_id
    tournamentGamesOnlyParam: tournament_games_only
